### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TrySound** [w0rm/gulp-postcss#24]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
ReferenceError: Promise is not defined
    at LazyResult.async (D:\_host\fl\teinvest\root\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.js:93:31)
    at LazyResult.then (D:\_host\fl\teinvest\root\node_modules\gulp-postcss\node_modules\postcss\lib\lazy-result.js:56:21)
    at Transform.stream._transform (D:\_host\fl\teinvest\root\node_modules\gulp-postcss\index.js:44:10)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Transform.Writable.write (_stream_writable.js:183:11)
    at write (D:\_host\fl\teinvest\root\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readabl
e.js:623:24)
    at flow (D:\_host\fl\teinvest\root\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable
.js:632:7)

```

**Comment by w0rm** [comment]
To use with node.js 0.10 add a polyfill for Promise. This is mentioned in readme.
