### ISSUE TITLE
Unable to use cssnext as a processor with gulp-postcss

### ISSUE THREAD

**Issue by kabadesu** [w0rm/gulp-postcss#26]
I'd like to use the cssnext plugin pack with gulp-postcss, as my first processor to be followed by a set of other cherry picked postcss plugins. The trouble is that I can't figure out how to get cssnext working with gulp-postcss. In the following code snippet I think I'm using `cssnext()` wrong within the `processors` array, but everything I've tried to correct it fails.

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var cssnext = require('cssnext');

config = {
  cssDistPath: './dist/css',
  cssSrcGlob:  './src/css/**/*.css'
};

gulp.task('css', function () {

  var processors = [
    cssnext({
      features: {
        calc: {
            preserve: true
        }
      }
    })
  ];

  return gulp.src(config.cssSrcGlob)
    .pipe(postcss(processors))
    .pipe(gulp.dest(config.cssDistPath));

});
```

Do you have any suggestions on how to get this working, or a better configuration?

**Comment by TrySound** [comment]
@kabadesu Give us log of your error, please.

**Comment by kabadesu** [comment]
@TrySound, sorry here:

```
 [TypeError: object is not a function]
  name: 'TypeError',
  message: 'object is not a function',
  stack: 'TypeError: object is not a function\n    at LazyResult.run (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:152:24)\n    at LazyResult.asyncTick (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:80:29)\n    at processing.Promise.then._this2.processed (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:106:20)\n    at $$$internal$$initializePromise (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:351:9)\n    at new $$es6$promise$promise$$Promise (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:655:9)\n    at LazyResult.async (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:105:27)\n    at LazyResult.then (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:68:21)\n    at Transform.stream._transform (/Users/murray/Development/postcss/node_modules/gulp-postcss/index.js:44:10)\n    at Transform._read (_stream_transform.js:179:10)\n    at Transform._write (_stream_transform.js:167:12)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-postcss' }
```

**Comment by ai** [comment]
@kabadesu can you post `error.stack` content. It is difficult too read it there.

**Comment by ai** [comment]
Seems like problem with Prmise polyfill.

Quick fix is to migrate to node 0.12 or io.js.

**Comment by kabadesu** [comment]
@ai I'm not sure how to get `error.stack` content, sorry. I'm not amazing at JavaScript. I using `console.trace` if that helps any?

```
Trace: { [TypeError: object is not a function]
  name: 'TypeError',
  message: 'object is not a function',
  stack: 'TypeError: object is not a function\n    at LazyResult.run (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:152:24)\n    at LazyResult.asyncTick (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:80:29)\n    at processing.Promise.then._this2.processed (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:106:20)\n    at $$$internal$$initializePromise (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:351:9)\n    at new $$es6$promise$promise$$Promise (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:655:9)\n    at LazyResult.async (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:105:27)\n    at LazyResult.then (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:68:21)\n    at Transform.stream._transform (/Users/murray/Development/postcss/node_modules/gulp-postcss/index.js:44:10)\n    at Transform._read (_stream_transform.js:179:10)\n    at Transform._write (_stream_transform.js:167:12)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-postcss' }
    at Transform.errorHandler (/Users/murray/Development/postcss/gulpfile.js:17:11)
    at Transform.emit (events.js:117:20)
    at onwriteError (_stream_writable.js:238:10)
    at onwrite (_stream_writable.js:256:5)
    at WritableState.onwrite (_stream_writable.js:96:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at handleError (/Users/murray/Development/postcss/node_modules/gulp-postcss/index.js:68:7)
    at $$$internal$$tryCatch (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:304:16)
    at $$$internal$$invokeCallback (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:316:17)
```

I'll have a go at node 0.12

**Comment by kabadesu** [comment]
In node 0.12.2 I get the following error:

```
Trace: { [TypeError: object is not a function]
  name: 'TypeError',
  message: 'object is not a function',
  stack: 'TypeError: object is not a function\n    at LazyResult.run (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:152:24)\n    at LazyResult.asyncTick (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:80:29)\n    at processing.Promise.then._this2.processed (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:106:20)\n    at LazyResult.async (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:105:27)\n    at LazyResult.then (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:68:21)\n    at Transform.stream._transform (/Users/murray/Development/postcss/node_modules/gulp-postcss/index.js:44:10)\n    at Transform._read (_stream_transform.js:179:10)\n    at Transform._write (_stream_transform.js:167:12)\n    at doWrite (_stream_writable.js:301:12)\n    at writeOrBuffer (_stream_writable.js:288:5)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-postcss' }
    at Transform.errorHandler (/Users/murray/Development/postcss/gulpfile.js:17:11)
    at Transform.emit (events.js:129:20)
    at onwriteError (_stream_writable.js:317:10)
    at onwrite (_stream_writable.js:335:5)
    at WritableState.onwrite (_stream_writable.js:105:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at handleError (/Users/murray/Development/postcss/node_modules/gulp-postcss/index.js:68:7)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
```

**Comment by ai** [comment]
@kabadesu please get stack by `console.log(error.stack)`

**Comment by ai** [comment]
`error.stack` already has all trace

**Comment by kabadesu** [comment]
```
TypeError: object is not a function
    at LazyResult.run (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:152:24)
    at LazyResult.asyncTick (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:80:29)
    at processing.Promise.then._this2.processed (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:106:20)
    at LazyResult.async (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:105:27)
    at LazyResult.then (/Users/murray/Development/postcss/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:68:21)
    at Transform.stream._transform (/Users/murray/Development/postcss/node_modules/gulp-postcss/index.js:44:10)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
```

**Comment by ai** [comment]
It is not a Promise polyfill problem. Seems like some `plugin` is object,

**Comment by ai** [comment]
@w0rm can I left it on you? I need to prepare to tomorrow flight

**Comment by w0rm** [comment]
I will take a look at this tonight

**Comment by w0rm** [comment]
@ai does it mean I should revert to previously used  `processors.forEach(processor.use.
bind(processor))` instead of `postcss(processors)`?

**Comment by ai** [comment]
@w0rm I think both methods will have same result. But `forEach` seems like more compilcated.

**Comment by w0rm** [comment]
@ai  it silently failed for me, but when I changed `postcss(processors)` to `var processor = postcss(); processors.forEach(processor.use. bind(processor))` then it worked. Don't know what should be the test case.

**Comment by w0rm** [comment]
Published 5.0.1, @kabadesu please verify the fix

**Comment by kabadesu** [comment]
You are amazing, that did the trick. Thanks everyone.

**Comment by Sigizmund2012** [comment]
Hello! I have same problem with gulp-replace plugin https://github.com/lazd/gulp-replace Do you have any idea to solve this?

**Comment by TrySound** [comment]
@Sigizmund2012 I'm not sure this is the same problem. Ask in gulp-replace repo.

**Comment by Sigizmund2012** [comment]
Ok, I write him an issue https://github.com/lazd/gulp-replace/issues/60

**Comment by hussienliban** [comment]
I believe I'm having the same issue, I'm using 6.0.0

Here's my setup

```
var gulp      = require('gulp'),
    postcss   = require('gulp-postcss'),
    cssnext   = require('gulp-cssnext');


var processors = [
        cssnext({
            'browers':          ['last 2 version'],
            'customProperties': true,
            'colorFunction':    true,
            'customSelectors':  true,
            'sourcemap':        true,
            'customProperties': true,
            'compress':         false
        })
    ];

gulp.task('css:dev', function(){
  return gulp.src('app/assets/css/main.css')
             .pipe(postcss(processors))
             .pipe(gulp.dest('build/assets/css/'));
});

```
And the error

```
/media/azuki/Kuma/Projects/buildsys/node_modules/gulp-postcss/node_modules/postcss/lib/processor.js:62
                throw new Error(i + ' is not a PostCSS plugin');
                      ^
Error: [object Object] is not a PostCSS plugin
    at Processor.normalize (/media/azuki/Kuma/Projects/buildsys/node_modules/gulp-postcss/node_modules/postcss/lib/processor.js:62:23)
    at new Processor (/media/azuki/Kuma/Projects/buildsys/node_modules/gulp-postcss/node_modules/postcss/lib/processor.js:25:29)
    at postcss (/media/azuki/Kuma/Projects/buildsys/node_modules/gulp-postcss/node_modules/postcss/lib/postcss.js:55:12)
    at Transform.stream._transform (/media/azuki/Kuma/Projects/buildsys/node_modules/gulp-postcss/index.js:43:5)
    at Transform._read (_stream_transform.js:179:10)
    at Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Transform.Writable.write (_stream_writable.js:217:11)
    at write (/home/azuki/.npm-packages/lib/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

```

**Comment by TrySound** [comment]
@hussienliban gulp-cssnext is wrapper on gulp. It's not postcss plugin. Use https://github.com/cssnext/postcss-cssnext

**Comment by hussienliban** [comment]
@TrySound  thank you
